### ISSUE TITLE
RFC: How to handle (exploration of) executions

### ISSUE THREAD

**Issue by 0x-r4bbit** [machinelabs/machinelabs#191]
## Objective

As part of  #187 we had longer discussions about how to make existing executions of labs for certain users accessible through the UI. During that discussion we unveiled a fair amount of problems with how we're enabling users to (re)visit, run and stopping executions. This RFC is an attempt to propose a concept on how to solve these problems and what conceptual changes are required to implement these.

## Motivation

Right now, there's no way for users to revisit existing executions of some labs. Even worse, users therefore can't stop those executions either and end up having plenty executions in limbo without being able to reach them.

**Here's what can happen**:

ML wants to allow users to play around with labs, making small changes and run those changes before actually saving those. Sometimes a user maybe just want to see if her code compiles. That's why as of right now, it's not necessary to save a lab to execute it. Users can take a lab, change it to their needs, execute it and simply leave the app. ML is going to take the contents of the lab (directories and files) to perform the execution.

At this point we have a problem. There's an execution for a lab that can't really be reached anymore. Users can't open the lab again because there's no associated ID, since the lab hasn't been saved. However, the execution is still there and might even still be running.

That's why in #187 we proposed to introduce a new view in which users can see all their running executions and get an overview of what's actually going on. While this is a crucial part of ML, it introduce another set or problems. When going through the list of executions, users probably want to revisit an execution and open it in the editor again so they can observe its status. However, the associated labs haven't been saved as such, leading us to recreate an actual lab from an existing execution. This can be confusing again because since there's no saved lab, we technically end up at `/editor` while seeing that (unsharable) execution.

Another thing that is problematic is that technically, there can be multiple different executions for the same lab. For example when starting with one lab, performing an execution, then making changes, performing an execution again. Now we have two executions for exactly the same lab with maybe different output but there's no way to access all of them.

## Goals

The goal is to change ML's UI/UX in a way that 

- it becomes obvious that there's existing executions for a certain lab
- existing executions can be easily revisited
- we never end up having executions for labs that don't exist (unsaved)
- only owners can execute their own labs (more on that in another issue)

## Implementation

In order to solve these issues, we came up with the following concept.

- Labs are always saved at least once - To perform an execution, a lab has to be saved. It needs to have an ID so that possible executions can be associated with it in the future. This mean clicking "New" or "Launch editor" automatically save the lab for the users. Forking a lab already saves it automatically.

- Only owners can execute their labs - This makes sure we don't run into the confusing case that when hitting "Play" a user gets the execution from another user. This is right now possible because ML first checks if there's already an execution for exactly the same lab contents. In order to execute a lab from someone else, you have to fork it, essentially making it your own.

- Executions can be performed any time - We remove the "Stop" from the toolbar. This basically means if a users hits "Play" a new execution is scheduled (already the case), but now the execution shows up in the sidenav as well. Now, when a user makes changes and hits run again, that's gonna be just yet another execution which also shows up in the sidenav. The users now has a the option to jump back and forth between executions by clicking on them, causing the editor to update its code and console output. This way, users always see multiple versions of their labs/executions on that particular lab and can compare "branches" of their experiments. From there, executions can also be stopped. **This also means that every "Run" is automatically a force-run**

If one is interested in seeing a cached output, one has to select that particular execution, which is now available in the UI.

## Action Items

- [x] Make sure labs are always saved at least once (#192)
- [x] Remove stop button from toolbar (#193)
- [x] Remove play button if user doesn't own lab (#194)
- [x] Change communication protocol for starting executions (#199)
- [x] Play button causes force-run (#178)
- [x] Show all executions of a lab in the sidenav (#195)
- [x] Make executions selectable, hydrating the editor with the executions contents and output (can be live output) (#195)
- [x] Select correct execution from deeplink URL (#196)
- [ ] ~~Allow users to give their executions names~~ (#197)
- [x] Change communication protocol for stopping executions (#198)
- [x] Add stop button to execution card so users can stop running executions (#195)
- [x] we might want a restart button as well (#178)
