### ISSUE TITLE
feat: user profile view

### ISSUE THREAD

**Issue by 0x-r4bbit** [machinelabs/machinelabs#66]
As of right now, Labs are created whenever we save or fork them. If we want to view or execute a lab that has been created in the past, there's no way to easily find it, apart from remembering the id or url of that lab.

That's why we should have a user profile page in which a logged-in user can view all owned labs as well as fav'ed/liked ones. 
### Tasks

- [x] create new method `LabStorageService.getLabsFromUser(user: User)`
- [x] create new route `/:username` (or `/user/:username`, or `/user/:userId`, thoughts?)
- [x] add link to toolbar menu that links to user profile
- [x] change user info template to link to profile once #94 landed
- [x] create `UserProfileComponent` (maybe consider refactor into own `NgModule` afterwards)
  - [x] render available user profile data and avatar
  - [x] render list of owned labs (like github profile)
  - [ ] render list of liked/fav'ed labs
    - right now, we don't have any data structures for likes/favs, so we'd need to introduce these. Let's discussed this!
  - [x] add link/button that allows user to create a new lab
- [ ] Liked/fav'ed filter should be represented in url so deep links work (e.g. `/user/:username?labs-filter=liked,forked, ...`)
- [x] write tests 
- [ ] we'll figure out UI/Design afterwards

---------

Similar to codepen or plunker. Here are some screen shots to give some ideas:

![screen shot 2017-03-30 at 12 57 33](https://cloud.githubusercontent.com/assets/445106/24501127/88fa1ad0-1548-11e7-9c3d-b66255dc6741.png)
![screen shot 2017-03-30 at 12 57 41](https://cloud.githubusercontent.com/assets/445106/24501137/8b445472-1548-11e7-9368-811a03567b1a.png)
